remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Monte Carlo Trading Strategy
description: Daily trading signals and strategy parameters
show_downloads: false

github:
  is_project_page: true
  repository_url: https://github.com/ajey091/monte-carlo-for-investing