name: Daily Trading Signals

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-signals:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Check requirements.txt content
      run: cat requirements.txt
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib
        pip install -r requirements.txt
        
    - name: Generate trading signals
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python strategy_monitor.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add daily_signals/*
        git commit -m "Update daily trading signals" || exit 0
        git push