name: Trading Signals Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-signals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # or whatever branch you want to use
          token: ${{ secrets.GITHUB_TOKEN }}  # Use this instead of ssh-key
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run strategy monitor
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python strategy_monitor.py
      
      - name: Update website data
        run: |
          cp best_parameters.json docs/_data/parameters.json
          cp daily_signals/signals_$(date +%Y-%m-%d).json docs/_data/signals.json
      
      - name: Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Fetch latest changes
          echo "Fetching latest changes..."
          git fetch origin gh-pages-v2
          
          # Pull with rebase
          echo "Pulling with rebase..."
          git pull origin gh-pages-v2 --rebase
          
          # Add and commit changes
          echo "Adding and committing changes..."
          git add daily_signals/* docs/_data/*
          git status  # Let's see what's actually being committed
          git commit -m "Update trading signals" || echo "No changes to commit"
          
          # Push with force if needed, but with lease for safety
          echo "Pushing changes..."
          git push --force-with-lease origin gh-pages-v2